### ISSUE TITLE
Consider adding more centralized org structure

### ISSUE THREAD

**Issue by michielbdejong** [indiehosters/documents#15]
I think we're not as professional as we could be at developing our franchise infrastructure. The way we are organized now, we are a migration network with hardly any code reuse. Without code reuse, there are two things that will not work:

* economies of scale on infrastructure development (each hoster will spend resources on reinventing the wheel)
* quality assurance (each hoster will have different bugs)

So let's brainstorm about how we can do better! One thought I had yesterday would be a three-level org, inspired mostly on Mozilla:

* a non-profit in some country, owning the ~~IP~~ brand (all code and knowledge open source, of course)
* a for-profit in probably the same country, owned by the non-profit, providing education and contributing as needed to the tools we use.
* the actual hosters who follow the education for free, then pay a small proof-of-work fee (like 200 euros) for certification, and then receive sales leads through the central indiehosters.net website.

I'm not sure whether in the Mozilla case the money that comes in goes first to the non-profit, and the for-profit is then contracted, or maybe the non-profit licenses the IP to the for-profit, which then directly receives the income.

But the main idea would be to set up a central non-profit, to make sure our infrastructure is built out in a organized (not chaotic) way. Or we can just stay as a migration network as we are now...

@pierreozoux what do you think?

**Comment by michielbdejong** [comment]
The for-profit would make money from taking a commission on the sales leads, or some other construction which amounts to a franchise fee. This money would be spent on expanding the brand. But the non-profit would guarantee that:

* everything is open source
* end-users get all the best personal server software
* end-users are encouraged to use their personal server and discover new software tools.

For end-users, it would be probably as most like being subscribed to a computer magazine, like the ones you see at kiosks, but aimed at autonomous internet usage. But instead of the "magazine" coming with a CD or a floppy disk, it comes with a personal server. :)

**Comment by pierreozoux** [comment]
Yes, we have to discuss about it. I agree on the ideology, but then, we'll need to find time to implement it.

**Comment by pierreozoux** [comment]
I thought a lot about it lately, and I think we have to tackle this at a greater scale.
There are many issues we are not the only one to solve. And we should collaborate together to tackle them.

issues that come to my mind:
 - provision domain name - API to registrar - metaregistrar
 - renew domain name
 - ssl certificate (then it will be let's encrypt)
 - SSO
 - migration format
 - application packaging
 - SNI

I think we have to contact other projects and discuss together about that. Here are the projects that come to my mind:
 - [clouder](https://github.com/clouder-community/clouder)
 - [archos](https://arkos.io/)
 - [yunohost](https://yunohost.org/#/)
 - [sandstorm](https://sandstorm.io/)
 - [ubos](http://ubos.net/)

I know we'll not be able to have the same infra, but at least, we should have the same migration format, and we can reuse piece of code one from another.

What do you think?

**Comment by michielbdejong** [comment]
Yes. And then we should also add IndiePaas and snickers as two separate projects. :) I think the first step towards code reuse is to use smaller units of product. I realised that it's not entirely true that we don't develop software. We have to develop the software that's missing. Software that exists, we only have to link/configure/package.

For automated signup and domain name registration, we need to use a CRM tool. I'm sure these exist and DNR and PayPal are standard plugins there. Also, tech support ticketing and billing ticketing. We need to use one professional tool for that (especially if we want to do each other's on-call shifts, this is a must).

Apart from that, we need provisioning and automated migration. I'm 50% sure there is *no* tool for that which fits our requirements, but I would be happy to be proven wrong. If anything, we could develop our automated migration as plugins for a popular open-source CRM tool, then others can benefit from it.

So far, this has nothing to do with the projects you mentioned, this is all still at the CRM/provisioning level.

Then the next thing we need is containers behind SNI. I'm 90% sure there is no open-source tool that does what snickers does (although I know Heroku has a closed-source tool for it, but I doubt whether that has LetsEncrypt-integration).

And then finally we need the actual packaged applications.

If you think logically about what we need then there is not much we can use these other projects for: none of them have developed something like the snickers container-aware SNI-offloader, and none of them have developed something like a CRM/deploy/migrate tool.

But it's not the end of the world, snickers is a pretty small and simple application to develop, and CRM tools exist elsewhere. The economies of scale are mainly in application packaging.

I believe it's best to use one container per application, because that makes it easy to stop and start. So that rules out IndiePaaS and Clouder for one-to-one code reuse of packaged applications. In any case, the place to reuse application images is on the Docker registry. Of course we want to use the mailserver from IndiePaas, which is itself reused, from mailinabox, right? And for Cozy and BuddyCloud for instance, we can also reuse existing Docker images.

The one application container should self-initialize if you mount an empty /data folder into it, and should have a script to dump its database, and to prepare for graceful shutdown. Nobody else is packaging apps that way, afaik. But it's possible to adapt existing Dockerfiles to fit those requirements.

The migration format is defined per-application, it's usually db dump + files. So we can only be compatible with ubos if they use the same application packages. If they use *similar* application packages, on an independent update cycle then we will be partially compatible (it will be easy to convert between the two). That's more or less the case for IndiePaaS and Snickers now, I think.

Now the good news about outbound code reuse:

* we have already contributed to developing Known's migration format
* I am now the maintainer of node-letsencrypt (a bugfixing fork of node-acme). This is only reusable in nodejs though, python-based project should use their python lib
* I am redesigning snickers-proxy in such a way that it's a stand-alone product, and also aim to publish its core functionality as npm packages, for more granular code reuse.

The good news about inbound code reuse:

* I'm basing all Dockerfiles on Dockerfiles and install instructions I find elsewhere, so it's not really like each application is packaged from scratch. I'm still planning to try again to get the mailserver from IndiePaaS working, and to reuse that. My attempts to reuse your code there have already lead to 3 or 4 documentation fixes, as you know.
* I'm using existing npm modules for everything in snickers-proxy (for instance node-acme, to which I'm also contributing back), so that's very good code reuse. I'm hardly writing any new code there.

It's hard to reuse python code in a nodejs product. That's just the way it is in software development.

And in general, I think I'll sponsor snickers-application packaging via freelancer.com or similar platforms (I was already doing something like that last year when it was still called 3pp.io). Have to work out where to get the money for that, but that's my new plan (I also plan to pay freelancers to peer-review each other, and to pay IndieHosters for trying it all out, and for offering everything to end-users at below cost price)

**Comment by michielbdejong** [comment]
I think I skipped configuration management there :) So maybe the components of our product are:

* webshop
* customer relations management (sales, tech support, billing, user settings)
* per-user deploy jobs (sending dnr request and editing server config)
* per-server configuration management (adding/resizing servers, installing/updating software, installing monitoring scripts, configuring mail relay, managing ssh keys)
* monitoring (graphs, emails, sms, for the sysadmin)
* backups
* sysadmin handbook, tutorials, certification program, conferences
* server-wide services (mail, xmpp, ...)
* snickers proxy
* snickers application images

When I say 'snickers' in that list I don't mean it necessarily needs to be the one I now wrote in nodejs, we can replace it with haproxy once we know how to build that. I just mean an SNI offloader that is capable of starting and stopping the backend containers behind it on-the-fly.

**Comment by michielbdejong** [comment]
So far we have done the first 7 mostly manually, and focussed mostly on the last 3. Maybe it's an idea to ask several experts from the field which tools they recommend for these first seven tasks, I would expect there is a standard stack and best practice for this somehow. Because if you offer shared LAMP webhosting, then you have exactly these same first 7 problems. Actually you have the 8th one as well.

That is probably where we can reuse a lot of existing work. Not so much in the last two, I would expect.

**Comment by michielbdejong** [comment]
and i'm also thinking, it would probably make most sense to take a ticketing component, a payment component, and a graphing component, and then put those together into a custom ticketing/payment/monitoring interface. For instance, if a server's disk is full, you want to immediately display which users are using up most, and have a button to send them a message. If you have separate off-the-shelf tools for CRM and CM, then it's hard to create meaningful workflows across them.

**Comment by michielbdejong** [comment]
So that's where I see most of our development work. Because that's what decides how easy it will be for some smart teenager who runs an internet cafe in for instance Pakistan, to become an IndieHoster. That's where the value of the franchise lies.

The Snickers proxy and the packaged applications are sort of straight-forward compared with the automation of sysadmin workflows.

**Comment by pierreozoux** [comment]
## Yes, we develop at the end, because there is nothing on the shelf that fits our need.

# CRM tool
I agree, we need one, but for the billing, not to discuss with DNR nor provision a user. I think the CRM can plug to a wroking infra, just reading data.
I see DNR as a service, it's just yet another service on the side of certificate, mysql or filesystem.

These issues are also faced but all the mentionned project. Not as a project, but as a user. If I use YUNOHOST, how can I buy a DN? This is the same!
And I forgot to mention Reclaim hosting.

# modular
That's for sure, we have to be as modular as possible. This way it will be really easy to collaborate on each module.

# application package
I love the way discourse tackle the issue: https://github.com/discourse/discourse_docker and we have to lobby each app to go this way, and to lobby the mentionned project to lobby with us :)
Then, we achieve toghether a greater goal, fullfilling the dream of a packaged application that can run everywhere :)

# "I'm 90% sure there is no open-source tool that does what snickers does"
This is a classical PaaS problem. And this problem is solved by many people, in the docker world, there is this list: https://github.com/weihanwang/docker-ecosystem-survey/ (feel free to add/edit/complete)
I like developping IndiePaaS, mostly for learning, and also, because none of them is ready to host wordpress... (not 12 factor app). But I would prefer to use/adapt one of this project as there are used by many people...

# next step
I think we start to have a view of what's need to be done/studied. We could separate into different issues. And try to contact some of the projects to see how we can collaborate on a specific module?
For instance, we could start with something small: DNR registration or bigger like application packaging?

I let you diggest that, and we discuss again in 10 days :)

Cheers!

**Comment by michielbdejong** [comment]
>  If I use YUNOHOST, how can I buy a DN? This is the same!
> And I forgot to mention Reclaim hosting.

There are no software modules to develop here, this is pure integration, I think. You need a webshop, a CRM, and a DNR provider, and these three should be linked together. Once the CRM or the webshop has the DNR provider's API key, the actual action is a curl one-liner. The software that does the work is behind the DNR provider's API. So unless yunohost, reclaim, and we, all have the same webshop and the same CRM and the same DNR provider, there is no code to reuse there. And even if we did, then it would just be this one line of code we would be reusing.

It's different for other parts of the puzzle, but I think DNR automation is not something that can be reused. There is no more than one line of custom software involved. :) Does that make sense?

> what snickers does [...] This is a classical PaaS problem. And this problem is solved by many
> people, in the docker world, there is this list:
> https://github.com/weihanwang/docker-ecosystem-survey/ (feel free to add/edit/complete)

OK, so by saying 'what snickers does' I actually meant just the jitboot functionality, so starting the container /after/ the http request has reached the server. I could not find any other system there that list that does it. I commented on [the StackOverflow thread about it](http://stackoverflow.com/a/29457131/680454).

I'm going to split up snickers ever further, so I may even put a unix socket inbetween the LetsEncrypt part and the jitboot part, so that the two become separate building blocks to be reused and replaced, and they don't both have to be written in the same programming language (which is a big hurdle for reusability).

So maybe it helps to think not of one monolythic "the infrastructure", but a collection of about 10 "core tools" which we hook together to create the nodes of the indiehosters federated infrastructure.

There are for sure a number of design decisions we need to document, and then we can flesh out the requirements for each of the core tools. I think one important one is our unusual federated, migration-oriented architecture, which is very unusual and makes our needs different from classical scalability architecture. So each hoster has their own infrastructure, and can at any point remove the ties with all other hosters and keep running in exactly the same way. This has implications for how we design the CRM (it should have ways to show and change data from multiple user databases in one single user interface). It also has implications for how we host DNS (each IndieHoster node should be its own nameservers, and migrations should involve a nameserver change in the DNR).

Another design decision is the assumption that no personal server should need to run on multiple physical servers. If your personal server is so busy that a whole physical server can't host it, then you're probably a celebrity, and it's a stretch to call your blog 'personal' instead of 'brand/marketing/whatever'. This simplifies a lot of things. It means we don't need to build complicated load balancing other than the robustness that comes from the one-click migrations (if a server dies, just migrate everyone to another one).

And then there is the decision that we want to offer loads of sandbox applications, which users can use once a year or every day, and we want this to work efficiently. So the sandboxing has lead us to Docker, and the efficiency of very-low-usage application instances to socket activation.

The tools we need are roughly (I split it up into 20 parts here):

### automatic provisioning and user support:
* webshop
* cms with billing & tax report automation
* payment provider (outsourced)
* ticket system

### automatic infrastructure management
* web interface for the indiehoster to manage multple servers (also those of your "buddy" hosters with which you share oncall shifts)
* scripts for adding/deleting servers, and adding/deleting ssh keys which have access to them
* monitoring and alerts of basic server and application health stats
* user data backup and restore scripts
* user migrate scripts
* data mover (move the right user data to the right server)
* container management (create the right containers on the right server)

### basic infrastructure components
* IaaS (outsourced)
* dnr (outsourced)
* tls certs (outsourced)
* DNS hosting
* SNI web proxy
* socket activation

### applications
* email, jabber, and identity services
* all major blogging tools, file server tools, and niche personal server tools
* all major small framasoft-style tools like etherpad, zerobin, etc.

**Comment by YannickB** [comment]
Hello,

Just to add my two cents to the discussion, I completely agree with the need of CRM/Billing/Webshop to be integrated with the hosting infrastructure.

This is one of the key reasons I chose to develop Clouder directly on Odoo, and so far the result is awesome. Even if you don't develop your orchestrator directly on it, I strongly recommend to use Odoo for theses purposes, it'll save you a lot of time.

**Comment by michielbdejong** [comment]
Oh, great idea! So far I have created a repo for [bedouin-crm](https://github.com/michielbdejong/bedouin-crm) as a 40-line nodejs app that saves a web form to a JSON file, but it will make a lot of sense to use Odoo for writing configs, and reuse all their CRM-related modules.

Good opportunity to refresh my python knowledge! :)

**Comment by YannickB** [comment]
:) If you need some help or advices don't hesitate to ask

**Comment by michielbdejong** [comment]
I realized the webhosting automation is missing from Odoo. If you look at https://opensrs.com/integration/tools/ you would want at least one open source tool to be in that list, but there is none! Looking also at http://alternativeto.net/software/whmcs/?license=free and http://stackoverflow.com/questions/29315895/best-whmcs-open-source-alternative the closest thing is https://github.com/TheHostingTool/TheHostingTool but it seems to me we should go for Odoo and add modules for webhosting-automation to it.

@YannickB you are a python developer, right? Shall we work together on this? I saw you already do some very related stuff in Clouder!

**Comment by pierreozoux** [comment]
From email discussion:

I like this idea of spliting, because I think it will be difficult to agree on all parts of the infra. So the more we split, the more we'll be able to collaborate on small parts. Or maybe not between us, but other peoples.

I want to build a cluster. (https://coreos.com/blog/cluster-osi-model/)
And this is the only way to achieve auto scalability in the future. And to not have to worry at night because a server died.

We want to use to container and socket activation mechanism.

I think we have to discuss at really high level, and slowly going down to the technical solution.

I think we agree on this story:
A user comes to our website, get convinced, pay for the services, and get access to its services.
In the background, we'll communicate with a DNR to buy its domain name. And we'll create a tls cert for all its applications.

I think we agree on that. Meaning we need the following:
 - webshop (which we kind of already have, a really basic, but  )
 - a CRM for billing, taxes...
 - a distributed OS (I'll come back on that later)
 - packaged/containerized applications (WP, known, cozy, discourse...) - this we shouldn't care. We should lobby application builder to provide us good one, that can be reused by us, yunohost, goclouder, cozy, reclaim... Younameit. But it should be the responsibility of the application provider to give us a container that we can ship. In my opinion, we should lobby on that. It could be with PR also, and also with freelancing.

The distributed OS, I don't want to build it. Smarter people are building it, kubernetes, docker swarm, Mesos... I think all of this is thrilling, and I love developing my little PaaS but I do it for the sake of learning. I know I have to use one of them, but none is quite ready. Maybe in 6months. We have to wait to decide on that. But I love working on it to understand, what are the pain points. But yeah, it would make more sense to start working on adapting one of these to our needs.
From what I see, those are missing the following:
 - DNS
 - email services for the applications (they assume it should be handled by the application itself)
 - distributed filesystem - this I guess it will come shortly 

And of course, you can build this distributedOS from scratch, like with snickers, and I'm sure you love it, as much as I do love developing IndiePaaS, but well, we know it's not worth it 

So if you agree on this idea of distributed OS, then we can put this decision for later 

So then we can start working on finding a nice webshop: (prestahop, magento?).
Find a nice CRM: odoo?

And we can lobby them to provide us nice containers 

And then we use the already existing connector from the webshop to the CRM.
And then, when we found our perfect distributedOS, we use the CRM to distributedOS connector, or we develop this piece  and this piece will be reused by other people, I'm quiet sure!

It sounds like a plan for me 

I like also the solution of using neither IndiePaaS nor snickers, then, there is no ego fights, nor "preferences" fights. (I think I prefer operations and Devops over developing, and you are the opposite  so we need to use smartly our strengths together rather than things to compete)

Collaboration is not easy, but it's nice to learn!

And I think we have to focus on collaboration pieces first, and discuss of non collaborations later.

I'll split up this into various issues to discuss.

**Comment by michielbdejong** [comment]
OK, let's agree to keep our separate systems for the servers for now, and also keep our collections of application Dockerfiles separate for now, but start to collaborate on the webshop->CRM->DNR part.

We can revisit this issue in a couple of months, and see if we can maybe start one standard collection of Dockerfiles - assuming you will still be using Dockerfiles by then! :)

**Comment by YannickB** [comment]
@michielbdejong Regarding DNR, I answered you in the dedicated issue I'll also need this feature so yeah we can work together on this, with pleasure.

@pierreozoux 
Really interesting diagram and text on the coreos link, thanks.
Note that for the webshop you can use Odoo (again), I am planning to develop a flexible clouder module for this on the Odoo CMS. Really, don't bother with magento or prestashop for this, synchro will be difficult.

Also please take care of the CRM term, you don't do billing with CRM software CRM is only for prospection normally, this is an ERP we are speaking. 
I am all for collaboration about standardization of containers, currently on Clouder we have to fill the dockerfiles manually or in template modules, but they are non portable to other hosters.

It's funny to see on this thread all the questions I asked myself two years ago. I hope to have already found most of the answers, so I'll continue to bring you the ideas I found until now.

**Comment by michielbdejong** [comment]
> CRM is only for prospection normally, this is an ERP we are speaking. 

Good to know! I thought CRM meant basically "user database", but I guess it's more focused on sales leads, and less on existing accounts, then.

**Comment by pierreozoux** [comment]
Ok, I think we agree on that.
