### ISSUE TITLE
ERP

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/documents#16]
The ERP will be the central piece for an IndieHoster to manage everything around their business.

Requirements:
 - be connected with our paypal button (or webshop)
 - be connected with a DNR provider (to buy domain name automatically)
 - be connected with TLS provider (probably Let's encrypt)

We are considering [Odoo](https://github.com/odoo/odoo), but recommendations are welcome.

**Comment by michielbdejong** [comment]
Yeah, the more I think about it, the more I think we should try to make all our tools plug in to an existing system like Odoo, because a lot of them will be reusable.

TLS can be provisioned on-the-fly, that's how I have it now. But the domain needs to be added to a hosting server, and to two name servers, and a welcome email should be sent out.

**Comment by YannickB** [comment]
Todo for your requirement on Odoo : 

-Webshop and integration with paypal and other payment providers : native
-DNR : subdomain done with clouder, TODO for root domains
-TLS : with clouder we can manually specify certificates (if none, we make a self-generated one), TODO for getting automatically from TLS providers.

**Comment by pierreozoux** [comment]
Ok, we are now using odoo :)
I'm quiet happy except update feature :/
