### ISSUE TITLE
application packaging - container based

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/documents#18]
discussion about how we should package applications.
why should it be different on yunohost, arkos, sandstorm, goclouder, ubos.

Description of the problem:
We need one command to run any kind of app. This could be a docker run, or something similar. As we see a trend of application of adopting docker, this is a good news for us.
We need to find a way to differentiate what are user data, and application data.
We need to find a way to differentiate what are running data, and backup data. (you shouldn't backup running mysql data if you don't want problems)

Requirements - some thoughts on this:
 - description of user data, and application data (in wordpress wp-content for instance.)
 - The application container should self-initialize if you mount an empty folder into it. (in wordpress, you should populate wp-content/theme with a default theme)
 - should have a script to dump its database and backup in general
 - should be able to start from a backup

But more than that, the best would be that application owner maintain such dockerfile.

**Comment by michielbdejong** [comment]
Also,

* web applications should expose port 80 (for use behind a TLS offloader).
* it should send outgoing emails to (where? port 25 on the Docker gateway?)
* it should configure itself with the container's hostname as its domain name
* it should use the ADMIN_USERNAME and ADMIN_PASSWORD variables to configure the admin user
* it should not send out its own welcome email and password reset emails

**Comment by michielbdejong** [comment]
The big dividing question that is still us from merging https://github.com/michielbdejong/snickers-applications and https://github.com/IndiePaaS/IndiePaaS/tree/master/dockerfiles/services is the question of whether the database should run inside the container or in a linked one.

It seems that general consensus in the industry is to put the database in a separate container from the webserver, and although this is an unnecessary complication for us, maybe it's worth conforming with that, to avoid discussions about something that in the end doesn't matter that much. It would however add the following extra requirements:

* apart from the Dockerfile, provide a docker-compose file (previously fig), which defines how to link the database server, and which type of database server is needed.
* assume during initial setup that the database user is 'root', and no password is required
* pick its own database name, and create a database by that name during initial setup

**Comment by YannickB** [comment]
Note that there might a concept which can prevent the portability of containers, this is the concept of services.

For example, we may want to have only one container for a customer, but having two services in it (one for production and another for development for example) with different files. This case may be very difficult to move between hosters.
At first, I propose to standardize on the techno which build the containers (example Dockerfiles), so at least all providers build the same containers, even if after they manage it differently. It'll be a good first step and quite easy to do.

Regarding ports, they have to be managed and mapped by your orchestrator, you have no choice (they are managed in the graphical interface in Clouder).
For mail, I suggest you make a separated postfix container, this is the choice I made.

Note that build the container with dockerfile is only 50% of the container configuration, then you have to launch some system commands after the deployment to finish the configuration with the variables in your orchestrator (you can't put them in your dockerfile which is static). For example, configuration the admin account with email and password specified by the customer and stored in your orchestrator.

Regarding the database/application separation, I think you shall be able to manage both case. Either you make a link or you place both of them in the container, it shall be the choice of the customer which use your orchestrator. 

There is still a notion I need to implement in clouder, this is a notion of package : You want to install a package, and it automatically deploy for example two containers, one with the database, another for application, and it establish the link between them.

**Comment by michielbdejong** [comment]
> finish the configuration

yes, this is what the container should do at first run, taking arguments from environment variables like ADMIN_EMAIL (see [above](https://github.com/indiehosters/documents/issues/18#issuecomment-93470600)).

> notion of package

check out [docker-compose](https://docs.docker.com/compose/), it does exactly that.

**Comment by michielbdejong** [comment]
> Regarding ports, they have to be managed and mapped by your orchestrator, you have no choice
we could say the container should expose port 80

> Regarding the database/application separation, I think you shall be able to manage both case.
Ah, that's not a bad idea, maybe. If an external database is detected, then it is used; if not, then one is started inside the container. @pierreozoux would that be OK for you?

**Comment by pierreozoux** [comment]
Many things here.

## Container
The docker image is becoming the standard, and it's pretty good, so I think we'll keep that.
No matter if it is built with a dockerfile, on the command line or packer, we'll trust/lobby the application developer to give us a good docker image.

## Services
The notion of services is really important. As I already said, I love the [12 factor app](http://12factor.net/) and all the purposes of docker is to embrace this philosophy by simplifying the process.
That said, everything should be considered as a service.
Then we have to deal with service dependencies management. How to describe these dependencies.
There are various ways:
 - docker compose
 - systemd unit files
 - fleet unit file
 - panamax template
 - clouder
 - [app container pods](https://github.com/appc/spec/blob/master/SPEC.md#app-container-pods-pods)
 - bash script
 - snickers?

Some services are common like logging, file system, or emails (the ability for the app to send emails), some are more specific like mysql or redis.

IMHO, the role of the "distributedOS" is to provide the basic/common services. And then we can deploy our specific services on top.

## One docker images or various?

I think this is the wrong way to put the problem. In my opinion, the issue is: how do we monitor services inside docker container? If you use `supervisord`, you give this responsability to it. But at the host level, you are just monitoring supervisord. And this is what people don't like. They want to monitor every process from the host.
The other issue is that, you break the 12 factor app by putting various services in one docker container.
As Yannick said, the best is to provide choice to people, and provide 2 ways:
 - one that respect the 12 factor app, and you have one container per service
 - one that is more convinient/easier to use, and gives all the services in one container.

On this, I love the way discourse solves the problem for us: https://github.com/discourse/discourse_docker#single-container-vs-multiple-container

I believe all app should deliver us docker images this way, and then, every body will be happy.

## Conclusion
Should we start writing specs for our containers?
I'll need to setup a discourse for one of my client, so I can see what is missing in the discourse image for us, and let you know!

**Comment by YannickB** [comment]
Regarding docker-compose, yes I know I was meaning to support it in the graphical interface of Clouder.

Regarding the database/application separation, on Clouder this would be two distinct applications. Either the customer chose to use a separate database, and then the default database you configured would be used, or he chose the other application which will install a database inside the container.

**Comment by YannickB** [comment]
Thank you pierre for the link to 12 factor app, another concept I discovered thanks to you.

**Comment by michielbdejong** [comment]
As we agreed on the phone, from now on IndieHosters is no longer just a migration network, but (also) a collection of Docker images that behave in a certain way. I will update https://github.com/indiehosters/dockerfiles with the new images from https://github.com/michielbdejong/snickers-applications and fix the [two](https://github.com/michielbdejong/snickers-applications/issues/13) [issues](https://github.com/michielbdejong/snickers-applications/issues/14) we discussed.

**Comment by pierreozoux** [comment]
A post related to our issue: https://fhackts.wordpress.com/2015/02/09/public-virtual-appliance-repositories-docker-vs-turnkeylinux-vs-vmware-which-is-the-largest-community/?hc_location=ufi

**Comment by michielbdejong** [comment]
Yes, definitely relevant. Although our requirements are more strict than those of turnkeylinux.

**Comment by YannickB** [comment]
Hum I always forget about turnkeylinux. I don't know it in details, but from what I look here it might be interesting for the initial build image.

For an example with Clouder, I think we might use in some case the image of turnkeylinux instead of the image build with dockerfile, at least I'd like to give the choice to the users. We'll still need to execute the system command after to configure the image with the variables, but at least the image itself can become a standard.

**Comment by michielbdejong** [comment]
turnkeylinux also published all their applications on https://registry.hub.docker.com/repos/turnkeylinux/ although it looks like they didn't update them for a year.

For IndieHosters we now (since last week) use https://github.com/indiehosters/applications for everything.

I agree the way we can reuse existing packaging work is by basing our images off other people's images.

In the extreme case you can use a one-line Dockerfile:
````dockerfile
FROM some-upstream/some-application
````
and then our Dockerfile only expresses that that is the image we're reusing.

**Comment by fthiery** [comment]
Hi guys, @jfgigand (a friend of mine) writes http://gitted.io which is basically tackling the aspects of deployment, backup and restore, all based on the single dependency of git. 

The basic principle is that the git repo for an app contains the bash-based code required for managing configuration, creating backups (dumping database + files) or restoring them. And the nice part is that it basically hooks into git custom protocols (ext), so creating a backup is as simple as git fetch and deploying is as simple as git push. The current implementation automatically creates a LXC based container and deploys the software, but there should be options for other stuff like creating vmdk images, maybe docker, etc...

It's a very downsized picture (i am no developer of the project and don't fully understand it) but i sense there is something quite universal here in the sense that it is completely git based, making it highly social-compatible.

**Comment by pierreozoux** [comment]
Thanks @fthiery for the pointer.

We actually used git for a while, for user's backup. But at the end, it is a hassle. I realised it is not made for that. Not made for an hourly backup, and not made for binaries. Yes, because we are talking about an hourly backup of 20Gb maybe (owncloud). And how to get rid of data older than a month? I know it is possible, but it is a hassle!

I use now duplicity, and I'm really happy with that! And we have encryption for free!

And for the other part of the project (configuration management, deployment) we use docker to solve this problem.

For the multi machine management, for now, I have one machine, but tomorrow, we plan to have some sort of [cluster](https://coreos.com/blog/cluster-osi-model/) management tool, that still need to be picked.

But thanks :)

**Comment by YannickB** [comment]
Hello,

I am also fan of git-based backup, for now I use bup and I am quite happy with it.

**Comment by pierreozoux** [comment]
No incremental encrypted backups :/ Encryption is life nowadays!

**Comment by jfgigand** [comment]
Hi guys,

Thanks @fthiery for bring me into this interesting conversation. Machine packaging has been needed for quite sometime, and I have observed that it's not only a distribution problem but maintenance as well.
A standard will be effective if it also eases the way machines evolve from the inside (live config changes) and how that sysadmin work could be propagated through new and existing containers.

Sysconf was created because Dockerfiles are too static:
- they do not define how the live machine is setup, as you pointed out above
- they could not be used to *fix* an existing container
- they could not be used to setup/fix an existing non-container machine.
- Also, Dockerfiles are too monolitics: there is no conventional way to split the Dockerfile and COPY files into different groups for sharing between machine definitions.

As for Gitted, it is not meant for "heavy backup", but for *reproduction*. Git cannot manage real backups because of its "infinite integrity", as you pointed out. But it's good for human work such as machine configuration.

I have a question here: after spawning a new container out of a Dockerfile, after working on its live configuration, how do you save the changes back to the Dockerfile/repo?

How do you guys feel about the state-less approach of Docker, which look like "1 command = 1 machine", where state is either volume-mounted or meaning-less, isn't it?

**Comment by pierreozoux** [comment]
- they do not define how the live machine is setup, as you pointed out above
     - they could not be used to fix an existing container
     - they could not be used to setup/fix an existing non-container machine.
     - Also, Dockerfiles are too monolitics: there is no conventional way to split the Dockerfile and COPY files into different groups for sharing between machine definitions.

[App Container Spec](https://github.com/appc/spec) and [rkt](https://github.com/coreos/rkt) are fixing the first 2. (They are now backed by [google](https://groups.google.com/forum/#!topic/appc-dev/F1vAVfIyoys) and [VMware](https://coreos.com/blog/vmware-ships-rkt/))

As for the 2 last, I agree with you, and I think an approach with more traditional configuration management tool [is the way](https://microblog.pierre-o.fr/2015/i-truly-believe-that-the-future-of-dockerfile-is-packer), associated with Packer. There is a [good article](https://news.ycombinator.com/item?id=7067648) on that. But then it is still a wild world.. If big application maintainer (wordpress, owncloud..) provide a docker image, I'd be happy with that! Either if it is buillt with chef-packer or dockerfile, or commited directly from a live docker. Their app, their standard. Then, we can grab this reliable piece, describe the running env (if they don't provide the [app container executor](https://github.com/appc/spec/blob/master/SPEC.md#app-container-executor) we can add it.)

    I have a question here: after spawning a new container out of a Dockerfile, after working on its live configuration, how do you save the changes back to the Dockerfile/repo?

We don't, for now, we work exclusively on Dockerfiles. For the live system, the docker image is like a read only bin, that you start with `docker run nameofthebin`. If you want to modify the bin, you have to do it on your dev env. Test it, ship it to the registry, and update your bin in prod.

    How do you guys feel about the state-less approach of Docker, which look like "1 command = 1 machine", where state is either volume-mounted or meaning-less, isn't it?

More precisely, one process, one container. I think this is great, and actually the app spec gives the [pod](https://github.com/appc/spec/blob/master/SPEC.md#app-container-pods-pods) which greatly help to describe how to run your processes.

**Comment by michielbdejong** [comment]
Gitter looks cool! It does a bit more than what we want - we don't want to push to deploy and start containers, we want containers to be created and started last-minute. This is because most of our customers will not use most of the services we offer them most of the time.

We don't configure individual machines other than through environment variables, but data is built up in the databases they run. Each container has a backup script which dumps the database into a .sql text file, for easy diffing and backups.

We currently mount a /data folder from the host into the container for all user data, but this has the disadvantage that we have to duplicate for instance the WordPress plugins for everybody, and don't take advantage of aufs when people don't install custom plugins. Also, most of the wp-content folder will be identical to the install-time content for many instances, so I think we should consider using docker volumes after all (and then do the backup with --volumes-from).

We don't have a good way for truncating git history yet, so old-fashioned backups as @pierreozoux is already using are also a useful option. I use git for hourly backups (and if a .git folder gets to big, I delete and re-initialize it) and then also let the IaaS provider back up the host machine, for disaster recovery.

**Comment by jfgigand** [comment]
Thanks @YannickB about bup, I did not know it and it's a interesting approach for backups-in-time!

About the /data you pointed out, @michielbdejong, late-added files could be deduplicated by an asynchronous process, optimizing file locations/blanking across AUFS layers or BTRFS filesystem (see: https://btrfs.wiki.kernel.org/index.php/Deduplication ). What do you think?

@pierreozoux, you said "one process, one container", does it mean you have plenty of containers for any public service? A website, for example, with nginx, multiwatch, spawn-cfgi, cron...
If I understand the Docker philosophy, a machine is an executable with its dependency resources packed as a static FS. It is like using UNIX for its static parts and taking all state-related matters out of the machine.

But: the purpose of a machine is basically the holding of living state (static /usr, persisted /var/lib, volatile /run, half-persisted /var/logs, temporarily-persisted /var/cache...). This is complex because of the diversity of technologies and integration usecases, and UNIX has evolved to embrass them. If you take the state-related matters out, you are re-inventing them all (inter-process communication, log management, start/stop lifecycle...).

Sometimes it is needed... for most usages, it's not. A middle-sized company using internally a MediaWiki, for example, needs 1 single container for Nginx, php-fpm, mysql, cron and sshd. Sure, it doesn't hurt having these process groups in different cgroups, which is the purpose of systemd. The case is: for maintenance, we want to access/fix /etc/nginx, php.ini, check the running process, run MediaWiki CLI commands... How does one work with 5 containers?

**Comment by michielbdejong** [comment]
@jfgigand it's probably worth mentioning that there is not (yet) one agreed way of how IndieHosters packages applications. @pierreozoux likes the one-process-one-container architecture, I like the everything-in-one-box architecture. Hopefully we will choose one single approach in the future! (which is also why we spend time discussing it in tickets like this one)

**Comment by jfgigand** [comment]
Thanks @michielbdejong for clarifying this!
I believe this choice should remain open... If the matter is organizational ("one command to run any kind of app"), then an "app" is whatever "app" the user thinks it is. For some people there is a MySQL app, a PhpMyAdmin app, a Wordpress app, etc. (as they use it that way); for others, there is only a "wordpress blog" which of course implies a database but it's private to the blog app.

**Comment by michielbdejong** [comment]
I think the issue is that applications can in theory be defined with a set of restrictions on the Dockerfile, but in practice it will be hard to get consensus on this set of restrictions. And a situation where we can only host applications that we packaged ourselves is not good, because it will require us to do a lot of packaging and updating work all the time. So maybe we should give up this goal?

In the past we talked about generating systemd unit files so that they define the right volumes, env vars, and pre-shutdown command.

So then this applications repo would be one small config file per application, plus a little script to generate unit files (or upstart files, or docker-compose.yml files, or whichever other systems there are to manage containers).

The script could eventually be "polyglot", so that it can generate the necessary files to insert an Docker-hosted application into different types of architectures.

It would have to be generic enough to deal with the various instructions people put in the readme's of their Dockerfiles (mainly env vars, volumes, ports, and linking).

**Comment by michielbdejong** [comment]
I think the underlying problem is that we're trying to do something very similar to what the Docker registry is trying (lots of applications all packaged for Docker), but as we know, that registry is also not a panacea, and each packaged application interfaces with its environment in a different way. So we either impose one way to Docker-package, or we add a layer that deals with the differences.

**Comment by pierreozoux** [comment]
@jfgigand 

Answer for 'One process per container': I'm sure you are familiar with [12 factor app](http://12factor.net/) and the idea there is to build awesome application. For instance, if you rely on local filesystem, then you'll hit the wall at one point if you try to scale. But yeah, the theory is far from reality. Right now, I'm trying to separate at least DB and APP, to be able to offer HA in the future. For cron, I rely on the host. For logs, I didn't find good solution (as a lot of legacy app do not `stdout/stderr`). But the good thing about the FLOSS ecosystem is: there is a lot of lamp, and now, node stacks (that embrace 12factor). lamp breaks 12 factor when it comes to the FS. Again, the annoying thing about processes inside the container, is monitoring, why having 2 layers of monitoring? On the host and inside the container? I want just one :)

But we can share one container, with all inclueded. And then, people will be free to start just one container. And I'll be free to start 1 container per process :) Again, look at [Discourse](https://github.com/discourse/discourse_docker).

And yes, we should base our image on top of existing ones!

**Comment by pierreozoux** [comment]
As per here: https://github.com/indiehosters/applications/issues/52 I think the agreement is to use `docker-compose`.

I close the issue for now, but if you have any more thoughts, do not hesitate to share here ;)
