### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/documents#19]
It would be nice to have a monthly newletter for IndieHosters.
And this should include our personal newsletter also.

Do you plan to write a newsletter for your users?

What do you think?

**Comment by michielbdejong** [comment]
I don't really have much interesting news for my users. :) We could write about our efforts to agree on a packaging format, and how hard this turned out to be in practice. But it's quite a technical topic, and we want to offer a service to non-technical users, right? The only other news I can think of is that I migrated one of my servers from ssd to sata, but I don't know if that's very interesting either.

Maybe we have more news to blob about for other hosters than for our own users?

**Comment by pierreozoux** [comment]
I think it could be interesting to at least share uptime on a monthly basis,and also canary warrant.

And them, you can also say, ok now I offer cozy, if you want to try, please contact me.

And then, on IH newsletter, we can speak about plan to have common apps.

**Comment by pierreozoux** [comment]
I think newsletter is important at least to report uptime. When you have downtime then, you are reminded that you'll have to report to all your users and other hosters. And this is kind of a nice pressure.

But well, it is up to you.

I'll let you close the issue.
